export const VISIBILITY_FILTERS = {
  FILTER_ALL: 'FILTER_ALL',
  FILTER_COMPLETED: 'FILTER_COMPLETED',
  FILTER_INCOMPLETE: 'FILTER_INCOMPLETE',
};

// Commands for manipulating todos
export const COMMANDS = {
  DELETE: 'DELETE',
  EDIT: 'EDIT',
};
