export const VISIBILITY_FILTERS = {
  FILTER_ALL: 'FILTER_ALL',
  FILTER_COMPLETED: 'FILTER_COMPLETED',
  FILTER_INCOMPLETE: 'FILTER_INCOMPLETE',
};

// Commands for invoking modal
export const COMMANDS = {
  DELETE: 'DELETE',
  EDIT: 'EDIT',
  SIGN_IN: 'SIGN_IN',
  REGISTER: 'REGISTER',
};
